query Home {
  home {
    id
    landingTitle
    landingSubtitle
    landingQuotes {
      quoteText
      quoteAuthor
    }
    landingBanners {
      bannerTitle
      bannerText
      bannerImage {
        url
      }
    }
  }
}
