query Home {
  home {
    id
    landingTitle
    landingSubtitle
    quoteIcon {
      url
    }
    landingQuotes {
      quoteText
      quoteAuthor
    }
    landingBanners {
      bannerTitle
      bannerText
      bannerImage {
        url
      }
    }
    productContainer {
      id
      title
      productItem {
        bannerTitle
        bannerText
        bannerImage {
          url
        }
      }
    }
  }
}
