query Home {
  home {
    id
    landingTitle
    landingSubtitle
    quoteIcon {
      url
    }
    landingQuotes {
      id
      quoteText
      quoteAuthor
    }
    landingBanners {
      title
      text
      image {
        url
      }
    }
    serviceItems {
      id
      title
      text
      image {
        url
      }
    }
    contactDetails {
      title
    }
  }
}
